apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-configmap
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env: # 1
        - name: DB_USERNAME # 2
          valueFrom:
            secretKeyRef: # 3
              name: db-data # 4
              key: username # 5
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-data
              key: password
  restartPolicy: Never
  