apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-secret
spec:
  containers:
    - name: volume-container
      image: chentex/random-logger
      volumeMounts: # 1
      - name: secret-volume # 2
        mountPath: /etc/config/key.json # 3
        subPath: key.json # 4
  volumes: # 5
    - name: secret-volume # 6
      secret: # 7
        secretName: db-data # 8
        items: # 9
        - key: username # 10
          path: key.json # 11
  restartPolicy: Never
