apiVersion: v1
kind: PersistentVolume # 1
metadata:
  name: nfs-0001 # 2
spec:
  capacity:
    storage: 2Gi # 3
  accessModes: # 4
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # 5
  nfs: # 6
    server: <IP_SERVER> # 7
    path: /data/data-0001 # 8
