apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-container
spec:
  limits:
  - max:
      cpu: "400m"
      memory: "500Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    default:
      cpu: "300m"
      memory: "400Mi"
    defaultRequest:
      cpu: "50m"
      memory: "50Mi"
    type: Container
