apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range
spec:
  containers:
  - name: container-limit-range-01
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from container 01; sleep 10; done"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
  - name: container-limit-range-02
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from container 02; sleep 10; done"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
  - name: container-limit-range-03
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from container 03; sleep 10; done"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"            

